---
# This playbook deploys a simple standalone Tomcat 7 ot 8 with JDK 8

- hosts: remote 
  remote_user: root
  become: yes
  become_method: sudo

 # choice the tomcat version
  roles:  
#    -  tomcat8
    -  maven
