---
- name: Install Java 1.7 
  apt: name=default-jdk state=present 


- name: add group "tomcat" 
  group: name=tomcat 


- name: add user "tomcat" 
  user: name=tomcat group=tomcat home=/opt/apache-tomcat-8.0.50/
  become: True 
  become_method: sudo 

- name: Download Tomcat 
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.50/bin/apache-tomcat-8.0.50.tar.gz dest=/opt/



- name: Extract archive
  unarchive: src=/opt/apache-tomcat-8.0.50.tar.gz
             dest=/opt/
             remote_src=yes 



- name: Change ownership of Tomcat installation 
  file: path=/opt/apache-tomcat-8.0.50/ owner=tomcat group=tomcat state=directory recurse=yes
  

- name: creating a link
  file: src=/opt/apache-tomcat-8.0.50 dest=/opt/tomcat owner=tomcat group=tomcat state=link force=true

- name: Change ownership of Tomcat installation 
  file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: example copying file with owner and permissions
  copy:
    src: tomcat.conf
    dest: /etc/init/tomcat.conf
    owner: tomcat
    group: tomcat
    mode: 0755
- name: Make my directory tree readable
  file:
    path: /opt/apache-tomcat-8.0.50 
    mode: u=rwX,g=rX,o=rX
    recurse: yes


- name: systemd daemon-reload
  shell: initctl reload-configuration 


- name: Start Tomcat 
  service: name=tomcat state=started enabled=yes 

