---
- name: Download  maven
  get_url: url=http://apache.mirror.digitalpacific.com.au/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=/opt/


- name: Extract archive maven
  unarchive: src=/opt/apache-maven-3.3.9-bin.tar.gz
             dest=/opt/
             remote_src=yes 


  
- name: Symlink install directory maven
  file: src=/opt/apache-maven-3.3.9-bin path=/opt/maven state=link force=yes

- name: Installing Maven
  shell:  update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.3.9/bin/mvn 1001 
